# Generated by Django 4.2.2 on 2023-06-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='level',
            field=models.CharField(choices=[('B', 'B'), ('A', 'A'), ('C', 'C')], default='A', max_length=2, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='site',
            field=models.CharField(choices=[('Shanghai', 'Shanghai(EDS)'), ('Taganrog', 'BARS-Taganrog(EDS)'), ('Beijing', 'Beijing(EDS)'), ('Madurai', 'Madurai(EDS)'), ('Tambov', 'BARS-Tambov'), ('Kaluga', 'BARS-Kaluga(EDS)'), ('Moscow', 'BARS-Moscow(All Avionics)'), ('Hyderabad', 'Hyderabad(EDS)'), ('Info-Tech', 'Info-Tech'), ('Puetro Rico', 'Puetro Rico'), ('Kursk', 'BARS-Kursk(All Avionics)'), ('Bangalire', 'Bangalire(EDS)')], max_length=100, verbose_name='Site'),
        ),
    ]
