# Generated by Django 4.2.2 on 2023-06-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scData', '0002_alter_testplan_level_alter_testplan_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testexception',
            name='note',
        ),
        migrations.AlterField(
            model_name='testplan',
            name='level',
            field=models.CharField(choices=[('C', 'C'), ('A', 'A'), ('B', 'B')], default='A', max_length=2, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='site',
            field=models.CharField(choices=[('Hyderabad', 'Hyderabad(EDS)'), ('Madurai', 'Madurai(EDS)'), ('Beijing', 'Beijing(EDS)'), ('Tambov', 'BARS-Tambov'), ('Kaluga', 'BARS-Kaluga(EDS)'), ('Info-Tech', 'Info-Tech'), ('Puetro Rico', 'Puetro Rico'), ('Kursk', 'BARS-Kursk(All Avionics)'), ('Bangalire', 'Bangalire(EDS)'), ('Taganrog', 'BARS-Taganrog(EDS)'), ('Shanghai', 'Shanghai(EDS)'), ('Moscow', 'BARS-Moscow(All Avionics)')], max_length=100, verbose_name='Site'),
        ),
    ]
