# Generated by Django 4.2.2 on 2023-06-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scData', '0003_remove_testexception_note_alter_testplan_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexception',
            name='SWline',
            field=models.CharField(max_length=50, verbose_name='Uncoverd SW Line'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='level',
            field=models.CharField(choices=[('C', 'C'), ('B', 'B'), ('A', 'A')], default='A', max_length=2, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='site',
            field=models.CharField(choices=[('Taganrog', 'BARS-Taganrog(EDS)'), ('Madurai', 'Madurai(EDS)'), ('Beijing', 'Beijing(EDS)'), ('Shanghai', 'Shanghai(EDS)'), ('Tambov', 'BARS-Tambov'), ('Bangalire', 'Bangalire(EDS)'), ('Info-Tech', 'Info-Tech'), ('Hyderabad', 'Hyderabad(EDS)'), ('Kaluga', 'BARS-Kaluga(EDS)'), ('Moscow', 'BARS-Moscow(All Avionics)'), ('Kursk', 'BARS-Kursk(All Avionics)'), ('Puetro Rico', 'Puetro Rico')], max_length=100, verbose_name='Site'),
        ),
    ]
