# Generated by Django 4.2.2 on 2023-06-20 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scData', '0005_alter_testplan_level_alter_testplan_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='level',
            field=models.CharField(choices=[('A', 'A'), ('C', 'C'), ('B', 'B')], default='A', max_length=2, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='site',
            field=models.CharField(choices=[('Tambov', 'BARS-Tambov'), ('Info-Tech', 'Info-Tech'), ('Taganrog', 'BARS-Taganrog(EDS)'), ('Shanghai', 'Shanghai(EDS)'), ('Madurai', 'Madurai(EDS)'), ('Hyderabad', 'Hyderabad(EDS)'), ('Kursk', 'BARS-Kursk(All Avionics)'), ('Moscow', 'BARS-Moscow(All Avionics)'), ('Bangalire', 'Bangalire(EDS)'), ('Kaluga', 'BARS-Kaluga(EDS)'), ('Beijing', 'Beijing(EDS)'), ('Puetro Rico', 'Puetro Rico')], max_length=100, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='swLoad',
            field=models.ForeignKey(db_column='Load', on_delete=django.db.models.deletion.CASCADE, to='scData.load', verbose_name='Software Load'),
        ),
    ]
