# Generated by Django 4.2.2 on 2023-06-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scData', '0006_alter_testplan_level_alter_testplan_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexception',
            name='issue',
            field=models.CharField(choices=[('Y', 'Yes'), (' ', ' '), ('N', 'No')], default=' ', max_length=10, verbose_name='Issue'),
        ),
        migrations.AlterField(
            model_name='testexception',
            name='ucClassification',
            field=models.CharField(choices=[('other', 'Other'), ('PAS', 'Previously Analyzed Software'), ('DefenCode', 'Defensive Code'), ('TEL', 'Test Environment Limitation'), (' ', ' '), ('RCM', 'Requirement-Code Mismatch'), ('DeactCode', 'Deactivated Code'), ('IT', 'Incomplete Test')], default=' ', max_length=100, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='level',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='overSight',
            field=models.CharField(choices=[('Y', 'Yes'), (' ', ' '), ('N', 'No')], default=' ', max_length=3),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='site',
            field=models.CharField(choices=[('Kaluga', 'BARS-Kaluga(EDS)'), ('Puetro Rico', 'Puetro Rico'), ('Shanghai', 'Shanghai(EDS)'), ('Tambov', 'BARS-Tambov'), ('Moscow', 'BARS-Moscow(All Avionics)'), ('Info-Tech', 'Info-Tech'), ('Hyderabad', 'Hyderabad(EDS)'), ('Bangalire', 'Bangalire(EDS)'), ('Kursk', 'BARS-Kursk(All Avionics)'), ('Taganrog', 'BARS-Taganrog(EDS)'), ('Beijing', 'Beijing(EDS)'), ('Madurai', 'Madurai(EDS)')], max_length=100, verbose_name='Site'),
        ),
    ]
