# Generated by Django 4.2.2 on 2023-06-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scData', '0007_alter_testexception_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexception',
            name='issue',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), (' ', ' ')], default=' ', max_length=10, verbose_name='Issue'),
        ),
        migrations.AlterField(
            model_name='testexception',
            name='ucClassification',
            field=models.CharField(choices=[('PAS', 'Previously Analyzed Software'), (' ', ' '), ('IT', 'Incomplete Test'), ('other', 'Other'), ('DeactCode', 'Deactivated Code'), ('RCM', 'Requirement-Code Mismatch'), ('DefenCode', 'Defensive Code'), ('TEL', 'Test Environment Limitation')], default=' ', max_length=100, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='overSight',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), (' ', ' ')], default=' ', max_length=3),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='site',
            field=models.CharField(choices=[('Puetro Rico', 'Puetro Rico'), ('Beijing', 'Beijing(EDS)'), ('Moscow', 'BARS-Moscow(All Avionics)'), ('Shanghai', 'Shanghai(EDS)'), ('Madurai', 'Madurai(EDS)'), ('Kursk', 'BARS-Kursk(All Avionics)'), ('Kaluga', 'BARS-Kaluga(EDS)'), ('Bangalire', 'Bangalire(EDS)'), ('Tambov', 'BARS-Tambov'), ('Hyderabad', 'Hyderabad(EDS)'), ('Taganrog', 'BARS-Taganrog(EDS)'), ('Info-Tech', 'Info-Tech')], max_length=100, verbose_name='Site'),
        ),
    ]
