# Generated by Django 4.2.2 on 2023-06-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scData', '0008_alter_testexception_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexception',
            name='ucClassification',
            field=models.CharField(choices=[('PAS', 'Previously Analyzed Software'), ('DefenCode', 'Defensive Code'), ('TEL', 'Test Environment Limitation'), ('other', 'Other'), ('IT', 'Incomplete Test'), ('RCM', 'Requirement-Code Mismatch'), ('DeactCode', 'Deactivated Code'), (' ', ' ')], default=' ', max_length=100, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='level',
            field=models.CharField(choices=[('A', 'A'), ('C', 'C'), ('B', 'B')], default='A', max_length=2, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='site',
            field=models.CharField(choices=[('Shanghai', 'Shanghai(EDS)'), ('Moscow', 'BARS-Moscow(All Avionics)'), ('Bangalire', 'Bangalire(EDS)'), ('Taganrog', 'BARS-Taganrog(EDS)'), ('Puetro Rico', 'Puetro Rico'), ('Beijing', 'Beijing(EDS)'), ('Kursk', 'BARS-Kursk(All Avionics)'), ('Tambov', 'BARS-Tambov'), ('Madurai', 'Madurai(EDS)'), ('Kaluga', 'BARS-Kaluga(EDS)'), ('Hyderabad', 'Hyderabad(EDS)'), ('Info-Tech', 'Info-Tech')], max_length=100, verbose_name='Site'),
        ),
    ]
