# Generated by Django 4.2.2 on 2023-06-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scData', '0010_alter_testexception_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexception',
            name='issue',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), (' ', ' ')], default=' ', max_length=10, verbose_name='Issue'),
        ),
        migrations.AlterField(
            model_name='testexception',
            name='ucClassification',
            field=models.CharField(choices=[('IT', 'Incomplete Test'), ('other', 'Other'), ('TEL', 'Test Environment Limitation'), ('PAS', 'Previously Analyzed Software'), ('DefenCode', 'Defensive Code'), ('RCM', 'Requirement-Code Mismatch'), ('DeactCode', 'Deactivated Code'), (' ', ' ')], default=' ', max_length=100, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='overSight',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), (' ', ' ')], default=' ', max_length=3),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='site',
            field=models.CharField(choices=[('Kursk', 'BARS-Kursk(All Avionics)'), ('Bangalire', 'Bangalire(EDS)'), ('Madurai', 'Madurai(EDS)'), ('Hyderabad', 'Hyderabad(EDS)'), ('Tambov', 'BARS-Tambov'), ('Taganrog', 'BARS-Taganrog(EDS)'), ('Beijing', 'Beijing(EDS)'), ('Moscow', 'BARS-Moscow(All Avionics)'), ('Kaluga', 'BARS-Kaluga(EDS)'), ('Info-Tech', 'Info-Tech'), ('Shanghai', 'Shanghai(EDS)'), ('Puetro Rico', 'Puetro Rico')], max_length=100, verbose_name='Site'),
        ),
    ]
