# Generated by Django 4.2.2 on 2023-06-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scData', '0011_alter_testexception_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexception',
            name='issue',
            field=models.CharField(choices=[('N', 'No'), (' ', ' '), ('Y', 'Yes')], default=' ', max_length=10, verbose_name='Issue'),
        ),
        migrations.AlterField(
            model_name='testexception',
            name='ucClassification',
            field=models.CharField(choices=[(' ', ' '), ('RCM', 'Requirement-Code Mismatch'), ('DefenCode', 'Defensive Code'), ('TEL', 'Test Environment Limitation'), ('IT', 'Incomplete Test'), ('PAS', 'Previously Analyzed Software'), ('other', 'Other'), ('DeactCode', 'Deactivated Code')], default=' ', max_length=100, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='overSight',
            field=models.CharField(choices=[('N', 'No'), (' ', ' '), ('Y', 'Yes')], default=' ', max_length=3),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='site',
            field=models.CharField(choices=[('Tambov', 'BARS-Tambov'), ('Kursk', 'BARS-Kursk(All Avionics)'), ('Puetro Rico', 'Puetro Rico'), ('Madurai', 'Madurai(EDS)'), ('Beijing', 'Beijing(EDS)'), ('Shanghai', 'Shanghai(EDS)'), ('Moscow', 'BARS-Moscow(All Avionics)'), ('Bangalire', 'Bangalire(EDS)'), ('Kaluga', 'BARS-Kaluga(EDS)'), ('Taganrog', 'BARS-Taganrog(EDS)'), ('Hyderabad', 'Hyderabad(EDS)'), ('Info-Tech', 'Info-Tech')], max_length=100, verbose_name='Site'),
        ),
    ]
