# Generated by Django 4.2.2 on 2023-07-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scData', '0012_alter_testexception_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexception',
            name='issue',
            field=models.CharField(choices=[('Y', 'Yes'), (' ', ' '), ('N', 'No')], default=' ', max_length=10, verbose_name='Issue'),
        ),
        migrations.AlterField(
            model_name='testexception',
            name='ucClassification',
            field=models.CharField(choices=[('RCM', 'Requirement-Code Mismatch'), ('other', 'Other'), ('DeactCode', 'Deactivated Code'), (' ', ' '), ('PAS', 'Previously Analyzed Software'), ('TEL', 'Test Environment Limitation'), ('DefenCode', 'Defensive Code'), ('IT', 'Incomplete Test')], default=' ', max_length=100, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='level',
            field=models.CharField(choices=[('A', 'A'), ('C', 'C'), ('B', 'B')], default='A', max_length=2, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='overSight',
            field=models.CharField(choices=[('Y', 'Yes'), (' ', ' '), ('N', 'No')], default=' ', max_length=3),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='site',
            field=models.CharField(choices=[('Taganrog', 'BARS-Taganrog(EDS)'), ('Beijing', 'Beijing(EDS)'), ('Moscow', 'BARS-Moscow(All Avionics)'), ('Puetro Rico', 'Puetro Rico'), ('Hyderabad', 'Hyderabad(EDS)'), ('Bangalire', 'Bangalire(EDS)'), ('Madurai', 'Madurai(EDS)'), ('Shanghai', 'Shanghai(EDS)'), ('Tambov', 'BARS-Tambov'), ('Info-Tech', 'Info-Tech'), ('Kaluga', 'BARS-Kaluga(EDS)'), ('Kursk', 'BARS-Kursk(All Avionics)')], max_length=100, verbose_name='Site'),
        ),
    ]
