# Generated by Django 4.2 on 2023-07-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scData', '0013_alter_testexception_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexception',
            name='issue',
            field=models.CharField(choices=[(' ', ' '), ('N', 'No'), ('Y', 'Yes')], default=' ', max_length=10, verbose_name='Issue'),
        ),
        migrations.AlterField(
            model_name='testexception',
            name='ucClassification',
            field=models.CharField(choices=[(' ', ' '), ('other', 'Other'), ('DefenCode', 'Defensive Code'), ('IT', 'Incomplete Test'), ('PAS', 'Previously Analyzed Software'), ('DeactCode', 'Deactivated Code'), ('RCM', 'Requirement-Code Mismatch'), ('TEL', 'Test Environment Limitation')], default=' ', max_length=100, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='level',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='overSight',
            field=models.CharField(choices=[(' ', ' '), ('N', 'No'), ('Y', 'Yes')], default=' ', max_length=3),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='site',
            field=models.CharField(choices=[('Puetro Rico', 'Puetro Rico'), ('Kaluga', 'BARS-Kaluga(EDS)'), ('Moscow', 'BARS-Moscow(All Avionics)'), ('Taganrog', 'BARS-Taganrog(EDS)'), ('Madurai', 'Madurai(EDS)'), ('Hyderabad', 'Hyderabad(EDS)'), ('Info-Tech', 'Info-Tech'), ('Shanghai', 'Shanghai(EDS)'), ('Tambov', 'BARS-Tambov'), ('Bangalire', 'Bangalire(EDS)'), ('Beijing', 'Beijing(EDS)'), ('Kursk', 'BARS-Kursk(All Avionics)')], max_length=100, verbose_name='Site'),
        ),
    ]
