# Generated by Django 4.2 on 2023-07-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scData', '0014_alter_testexception_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexception',
            name='issue',
            field=models.CharField(choices=[(' ', ' '), ('Y', 'Yes'), ('N', 'No')], default=' ', max_length=10, verbose_name='Issue'),
        ),
        migrations.AlterField(
            model_name='testexception',
            name='ucClassification',
            field=models.CharField(choices=[(' ', ' '), ('DeactCode', 'Deactivated Code'), ('DefenCode', 'Defensive Code'), ('RCM', 'Requirement-Code Mismatch'), ('PAS', 'Previously Analyzed Software'), ('other', 'Other'), ('IT', 'Incomplete Test'), ('TEL', 'Test Environment Limitation')], default=' ', max_length=100, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='level',
            field=models.CharField(choices=[('B', 'B'), ('A', 'A'), ('C', 'C')], default='A', max_length=2, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='overSight',
            field=models.CharField(choices=[(' ', ' '), ('Y', 'Yes'), ('N', 'No')], default=' ', max_length=3),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='site',
            field=models.CharField(choices=[('Hyderabad', 'Hyderabad(EDS)'), ('Moscow', 'BARS-Moscow(All Avionics)'), ('Madurai', 'Madurai(EDS)'), ('Tambov', 'BARS-Tambov'), ('Kaluga', 'BARS-Kaluga(EDS)'), ('Bangalire', 'Bangalire(EDS)'), ('Shanghai', 'Shanghai(EDS)'), ('Taganrog', 'BARS-Taganrog(EDS)'), ('Kursk', 'BARS-Kursk(All Avionics)'), ('Beijing', 'Beijing(EDS)'), ('Info-Tech', 'Info-Tech'), ('Puetro Rico', 'Puetro Rico')], max_length=100, verbose_name='Site'),
        ),
    ]
