# Generated by Django 4.2.2 on 2023-06-16 08:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Functionality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=10, verbose_name='Function')),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.CharField(max_length=50, verbose_name='Load')),
                ('Func', models.ForeignKey(db_column='Functionality', on_delete=django.db.models.deletion.CASCADE, to='scData.functionality')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50, verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='TestException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=50, verbose_name='Note')),
                ('module', models.CharField(max_length=50, verbose_name='Module')),
                ('function', models.CharField(max_length=50, verbose_name='Function')),
                ('line', models.CharField(max_length=500, verbose_name='Line')),
                ('reqTag', models.CharField(max_length=500, verbose_name='Requirement Tag')),
                ('analyst', models.CharField(max_length=50, verbose_name='Analyst')),
                ('ucClassification', models.CharField(choices=[('IT', 'Incomplete Test'), ('RCM', 'Requirement-Code Mismatch'), ('DeactCode', 'Deactivated Code'), ('DefenCode', 'Defensive Code'), ('TEL', 'Test Environment Limitation'), ('PAS', 'Previously Analyzed Software'), ('other', 'Other'), (' ', ' ')], default=' ', max_length=100, verbose_name='Class')),
                ('analysisSummary', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Analysis Summary')),
                ('correctiveAction', models.CharField(blank=True, default='No corrective action required.', max_length=300, null=True, verbose_name='Corrective Action')),
                ('issue', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), (' ', ' ')], default='No corrective action required.', max_length=10, verbose_name='Issue')),
                ('applicable', models.CharField(choices=[('PAR', 'PAR'), ('CR', 'CR'), ('N/A', 'N/A')], default='N/A', max_length=10, verbose_name='Applicable')),
            ],
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=50, null=True, verbose_name='Level')),
                ('process', models.CharField(max_length=50, verbose_name='Process')),
                ('fName', models.CharField(max_length=50, verbose_name='File Name')),
                ('func', models.CharField(max_length=50, verbose_name='Function')),
                ('analyst', models.CharField(max_length=50, verbose_name='Analyst')),
                ('site', models.CharField(max_length=50, verbose_name='Site')),
                ('startDate', models.DateTimeField(verbose_name='Start Date')),
                ('mcdcCoverage', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='MC/DC Coverage')),
                ('eventCoverage', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Event Coverage')),
                ('analysisCoverage', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Analysis Coverage')),
                ('totalScCoverage', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Total SC Coverage')),
                ('branches', models.IntegerField(verbose_name='Branches')),
                ('events', models.IntegerField(verbose_name='Events')),
                ('note', models.CharField(max_length=50, verbose_name='Note')),
                ('coveredDecisions', models.IntegerField(verbose_name='Covered Decisions')),
                ('coveredConditons', models.IntegerField(verbose_name='Covered Conditions')),
                ('coveredCases', models.IntegerField(verbose_name='Covered Cases')),
                ('coveredEvents', models.IntegerField(verbose_name='Covered Events')),
                ('totalDecisions', models.IntegerField(verbose_name='Total Decisions')),
                ('totalConditions', models.IntegerField(verbose_name='Total Conditions')),
                ('totalCases', models.IntegerField(verbose_name='Total Cases')),
                ('totalEvents', models.IntegerField(verbose_name='Total Events')),
                ('overSight', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), (' ', ' ')], default=' ', max_length=1)),
                ('tech', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tech')),
                ('nonTech', models.CharField(blank=True, max_length=50, null=True, verbose_name='Non-Tech')),
                ('processDefect', models.CharField(blank=True, max_length=50, null=True, verbose_name='Process Defect')),
                ('swLoad', models.ForeignKey(db_column='Load', on_delete=django.db.models.deletion.CASCADE, to='scData.load')),
                ('testException', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scData.testexception', verbose_name='Test Exception')),
            ],
        ),
        migrations.AddField(
            model_name='functionality',
            name='Project',
            field=models.ForeignKey(db_column='Project', on_delete=django.db.models.deletion.CASCADE, to='scData.project'),
        ),
    ]
