# Generated by Django 4.2.2 on 2023-06-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='Porject',
        ),
        migrations.RemoveField(
            model_name='functionality',
            name='Certification',
        ),
        migrations.RemoveField(
            model_name='load',
            name='Func',
        ),
        migrations.DeleteModel(
            name='TestException',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='swLoad',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Functionality',
        ),
        migrations.DeleteModel(
            name='Load',
        ),
        migrations.DeleteModel(
            name='TestPlan',
        ),
    ]
