# Generated by Django 4.2.2 on 2023-06-15 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scData', '0003_functionality_load_testexception_testplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='level',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], default='', max_length=50, null=True, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='testException',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scData.testexception'),
        ),
    ]
